const restaurant = {whatsapp:'962797191419',address:'عمّان، شارع الجامعة، مقابل البوابة الرئيسية، بناية رقم 271',maps:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('مطعم جمعة بلد عمان شارع الجامعة مقابل البوابة الرئيسية بناية 271')};
const groups=['شاورما','الوجبات العائلية','زنجر البلد','زرب ومندي','إضافات'];
const raw=[['وجبة عادي',2.25,0],['وجبة سوبر',2.75,0],['وجبة دبل',3.40,0],['وجبة دبل مكس',4,0],['وجبة تربل',4.50,0,'الأكثر مبيعًا'],['وجبة حلبي',3.75,0],['وجبة إيطالي',3.75,0,'الأكثر طلبًا'],['ساندويش صغير',.65,0,'عادي / شراك'],['ساندويش كبير',1.20,0],['ساندويش فرنسي',1.50,0],['شاورما عائلية · 32 قطعة',7,1,'بطاطا + كولا لتر + مثومة عادي وحار + مخلل'],['شاورما عائلية · 48 قطعة',11,1,'بطاطا + كولا لتر + مثومة عادي وحار + مخلل'],['شاورما عائلية · 64 قطعة',13,1,'بطاطا + 2 كولا لتر + 3 مثومة عادي + 3 حار + 3 مخلل'],['ساندويش زنجر البلد',1.75,2],['وجبة زنجر البلد',2.75,2],['وجبة زنجر إيطالي',4.50,2],['ساندويش بطاطا فرنسي',1,2],['ربع دجاجة / فخذة مع رز',2.50,3,'لبن + دقوس'],['ربع دجاجة / سفينة مع رز',3,3,'لبن + دقوس'],['نصف دجاجة مع رز',4.25,3,'لبن + دقوس'],['دجاجة كاملة مع رز',8.50,3,'2 لبن + دقوس'],['دجاجة ونصف مع رز',11.50,3,'3 لبن + دقوس'],['دجاجتين مع رز',16,3,'4 لبن + دقوس'],['ربع دجاجة / فخذة بدون رز',1.75,3,'دقوس'],['ربع دجاجة / سفينة بدون رز',2,3,'دقوس'],['نصف دجاجة بدون رز',3.75,3,'دقوس'],['صحن رز بدون دجاج',1.75,3,'دقوس'],['كولا',.30,4],['كولا لتر',.70,4],['ماء',.30,4],['مثومة',.50,4],['مخلل',.50,4],['دبس رمان',.50,4],['شطة',.50,4],['جبنة سائلة',.75,4],['بطاطا صغير',.75,4,'كاتشب'],['بطاطا كبير',1.25,4,'كاتشب']];
const menu=raw.map(([name,price,group,note],id)=>({id,name,price,group,note}));
const $=s=>document.querySelector(s),money=n=>n.toFixed(2);let category=-1,panel='order',cart={},toastTimer;
const count=()=>Object.values(cart).reduce((a,b)=>a+b,0),total=()=>menu.reduce((a,m)=>a+m.price*(cart[m.id]||0),0);
function qty(m){return `<div class="quantity"><button type="button" aria-label="تقليل ${m.name}" data-change="${m.id}" data-delta="-1">−</button><span>${cart[m.id]}</span><button type="button" aria-label="زيادة ${m.name}" data-change="${m.id}" data-delta="1">+</button></div>`}
function render(){
 $('#tabs').innerHTML=['كل الأصناف',...groups].map((g,index)=>{const i=index-1;return `<button type="button" aria-pressed="${i===category}" data-category="${i}" class="${i===category?'selected':''}">${g}${i===category?'<span>↙</span>':''}</button>`}).join('');
 $('#menu-items').innerHTML=menu.filter(m=>category===-1||m.group===category).map((m,i)=>`<article class="food-card"><div class="food-top"><span class="item-number">${String(i+1).padStart(2,'0')}</span>${m.note?.startsWith('الأكثر')?`<span class="popular">✦ ${m.note}</span>`:''}</div><h3>${m.name}</h3><p>${m.note&&!m.note.startsWith('الأكثر')?m.note:groups[m.group]+' جمعة بلد'}</p><div class="food-bottom"><strong>${money(m.price)} <small>د.أ</small></strong>${cart[m.id]?qty(m):`<button class="add" aria-label="أضف ${m.name} للسلة" data-change="${m.id}" data-delta="1">+</button>`}</div></article>`).join('');
 $('#cart-count').textContent=count();$('#basket-count').textContent=count();
 $('#basket-content').innerHTML=count()?`<div class="basket-items">${menu.filter(m=>cart[m.id]).map(m=>`<div><span>${m.name}<small>${cart[m.id]} × ${money(m.price)} د.أ</small></span><button aria-label="حذف قطعة من ${m.name}" data-change="${m.id}" data-delta="-1">−</button></div>`).join('')}</div><div class="basket-total"><span>مجموع الأصناف</span><strong>${money(total())} د.أ</strong></div><button class="primary full" data-open="order">راجع طلبك ↖</button>`:`<div class="empty-basket"><svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" aria-hidden="true"><path d="M5 7h14l1 14H4L5 7Z M8 7V5a4 4 0 0 1 8 0v2"/></svg><h4>الجمعة بتبلّش بلقمة</h4><p>ضيف اللي بتحبّه من المنيو،<br>وبنرتّب طلبك هون.</p></div>`;
 $('#checkout-items').innerHTML=menu.filter(m=>cart[m.id]).map(m=>`<div><span>${m.name}</span>${qty(m)}<b>${money(m.price*cart[m.id])}</b></div>`).join('');$('#checkout-total').textContent=money(total())+' د.أ';
 if($('#dialog').open&&panel==='order'){$('#dialog-empty').hidden=!!count();$('#request-form').hidden=!count();}
}
function openDialog(which){panel=which;const booking=which==='booking';$('#dialog-title').textContent=booking?'احجز للّمة':'خلّينا نرتّب طلبك';$('#order-fields').hidden=booking;$('#booking-fields').hidden=!booking;for(const id of ['date','time','guests']){$('#'+id).required=booking;$('#'+id).disabled=!booking;}$('#address').required=!booking&&$('#method').value==='توصيل';$('#confirm-note').textContent=booking?'طلب الحجز يخضع لتوفر الطاولات وتأكيد المطعم.':'الأسعار من المنيو المرفق وقابلة للتحديث عند تأكيد الطلب.';$('#dialog-empty').hidden=booking||!!count();$('#request-form').hidden=!booking&&!count();$('#notice').hidden=true;$('#dialog').showModal();}
document.addEventListener('click',e=>{const change=e.target.closest('[data-change]');if(change){const id=Number(change.dataset.change),delta=Number(change.dataset.delta);cart[id]=Math.max(0,(cart[id]||0)+delta);render();$('#toast').textContent=delta>0?'انضافت للسلة':'تم تحديث السلة';$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1800);const replacement=document.querySelector(`#menu-items [data-change="${id}"][data-delta="${delta}"]`)||document.querySelector(`#menu-items [data-change="${id}"]`);if(!$('#dialog').open)replacement?.focus({preventScroll:true});}const cat=e.target.closest('[data-category]');if(cat){category=Number(cat.dataset.category);render();$(`[data-category="${category}"]`).focus({preventScroll:true});}const opener=e.target.closest('[data-open]');if(opener)openDialog(opener.dataset.open);});
$('#family-menu').onclick=()=>{category=1;render()};$('#close-dialog').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#dialog').close();}});$('#browse-menu').onclick=()=>{$('#dialog').close();$('#menu').scrollIntoView({behavior:'smooth'});};$('#method').onchange=()=>{const delivery=$('#method').value==='توصيل';$('#delivery').hidden=!delivery;$('#address').required=delivery&&panel==='order';};
const now=new Date();$('#date').min=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
$('#request-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(panel==='booking'&&new Date(`${f.get('date')}T${f.get('time')}`)<=new Date()){$('#notice').textContent='اختار موعدًا قادمًا للحجز.';$('#notice').hidden=false;return;}let message=panel==='booking'?`طلب حجز — جمعة بلد\nالتاريخ: ${f.get('date')}\nالوقت: ${f.get('time')}\nالأشخاص: ${f.get('guests')}`:`طلب — جمعة بلد\n${menu.filter(m=>cart[m.id]).map(m=>`${cart[m.id]} × ${m.name}: ${money(m.price*cart[m.id])} د.أ`).join('\n')}\nمجموع الأصناف: ${money(total())} د.أ\n${f.get('method')}\nالعنوان: ${f.get('method')==='توصيل'?f.get('address'):'استلام من المطعم'}`;message+=`\nالاسم: ${f.get('name')}\nالهاتف: ${f.get('phone')}\nملاحظات: ${f.get('notes')}\nبانتظار تأكيد المطعم`;if(restaurant.whatsapp){window.open(`https://wa.me/${restaurant.whatsapp}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');$('#notice').textContent='أكمل إرسال الرسالة في واتساب. الطلب غير مؤكد حتى يرد المطعم.';}else{try{await navigator.clipboard.writeText(message);$('#notice').textContent='تم نسخ التفاصيل فقط، ولم تُرسل للمطعم. الإرسال متاح بعد اعتماد رقم التواصل.';}catch{$('#notice').textContent='تعذّر النسخ. رقم استقبال الطلبات لم يُعتمد بعد؛ لم يتم إرسال أي طلب.';}}$('#notice').hidden=false;};
if(restaurant.whatsapp){$('#availability').hidden=false;$('#submit-request').textContent='متابعة على واتساب ↖';}if(restaurant.address){$('#address-title').textContent=restaurant.address;$('#address-description').textContent='نتشرّف بزيارتكم. للطلبات والحجوزات تواصلوا معنا على الأرقام التالية.';}if(restaurant.maps){$('#maps-link').href=restaurant.maps;$('#maps-link').hidden=false;}render();
